export const state = {
  appTitle: 'Group Nine Media',
  user: null,
  error: null,
  loading: false,
  snackbar: null,
  airtableProjects: null,
  airtableDepartments: null,
  airtableTeams: null,
  airtableStatuses: null,
  airtableTasks: null,
  airtablePhases: null,
  airtableWeeks: null,
  airtableProjectFilter: [],
  airtablePhaseFilter: [],
  dispatchedStatuses: false,
  dispatchedProjects: false,
  dispatchedTeamsForTeamProjectList: false,
  dispatchedProjectsForTeamProjectList: false
}
